### ISSUE TITLE
Fatal error: Cannot redeclare class InstagramLatestPosts

### ISSUE THREAD

**Issue by fonpixel** [igorsuhinin/modx-instagram-latest-posts#11]
Здравствуйте, Игорь.
При попытке дважды вызвать сниппет на одной странице (2 разных аккаунта Instagram) возникает ошибка:
Fatal error: Cannot redeclare class InstagramLatestPosts in /home/user/website.com/core/cache/includes/elements/modsnippet/50.include.cache.php on line 27
версия InstagramLatestPosts - 1.6.0
MODX 2.6.1, PHP 5.6

**Comment by igorsuhinin** [comment]
Привет!

Да, проблему понял, исправлю в ближайшее время. Просто не думал, что кому-то может понадобиться вызывать сниппет дважды на одной странице :)

**Comment by igorsuhinin** [comment]
Вообще как быстрое решение, чтобы не ждать апдейта, можете сами добавить в код сниппета прямо вокруг описания класса
```
if (!class_exists('InstagramLatestPosts')) {
	class InstagramLatestPosts {
		...
	}
}
```

**Comment by fonpixel** [comment]
Теперь сниппет будет еще универсальнее )))
http://www.delicieux.co.in/
Возникла проблема с файлом кеша, который заполнялся значением первого вызова сниппета.
Для решения проблемы с одним общим кешем на 68-й строке изменил значение cacheDir
$this->cacheDir     = 'instagram_latest_posts-'.$config['accountName'];
Спасибо большое!

**Comment by igorsuhinin** [comment]
А, ну да, ну да... Все верно. Сниппет просто не предназначался для множественного вызова на одной странице :) В общем, да, это баг, будет исправлено в будущем релизе

**Comment by igorsuhinin** [comment]
@fonpixel В текущем релизе эти баги исправлены. Спасибо за помощь )
