### ISSUE TITLE
is_video

### ISSUE THREAD

**Issue by fonpixel** [igorsuhinin/modx-instagram-latest-posts#12]
При включенном параметре showVideo возникла проблема - все элементы ленты выводились как видео объекты. В сниппете нашел такую проверку:
`if (isset($node->is_video) && $this->showVideo) {`
но в Json файле instagram у каждого объекта этому параметру присвоено значение - или true или  false, то есть так или иначе, но isset по идее должен отработать как true
Убрал проверку isset
`if (($node->is_video) && $this->showVideo) {`
и проблема решилась.

Плюс пожелание к следующей версии. В чанке Instagram-Inner проверку типа заменить на сокращенную и добавить кнопочки к видео
`[[+type:is='image':then='<img src="[[+url]]" alt="" >':else='<video controls><source src="[[+url]]" type="video/mp4"></video>']]`
Там в любом случае только два типа

**Comment by igorsuhinin** [comment]
Привет!

Спасибо за замечания, все по делу. Вы могли бы отправить мне PR с этими
изменениями?

28 февр. 2018 г. 5:46 AM пользователь "fonpixel" <notifications@github.com>
написал:
