### ISSUE TITLE
The remote loading of JSON content failed.

### ISSUE THREAD

**Issue by MaximRoganov** [igorsuhinin/modx-instagram-latest-posts#18]
Hi,today i install you package and get snippet code from github.
Currently i have:
`Error: The remote loading of JSON content failed. Please check if your account name is correct.`
Do you have any idea to fix it?
ps 
i have normal and non private instagram account name

**Comment by makc9I** [comment]
Походу инстаграм прикрыл доступ по url с ключом ?__a=1, раньше таким образом мы получали json и дальше уже сниппет его парсил. Теперь же сама инста выдает 403юю...

**Comment by Shiyankin** [comment]
И что делать?

**Comment by MaksimRoganov** [comment]
We have one chance to mix current method with inwidget.ru
It have a one negative option: we need access to account which we wanna to show in our front

**Comment by Ilja-developer** [comment]
Same issue here.

Error log: PHP warning: file_get_contents(https://www.instagram.com/nike/?__a=1): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

Any ideas?

**Comment by MaksimRoganov** [comment]
> Same issue here.
> 
> Error log: PHP warning: file_get_contents(https://www.instagram.com/nike/?__a=1): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
> 
> Any ideas?

Why it happen
https://github.com/igorsuhinin/modx-instagram-latest-posts/issues/18#issuecomment-395666015

And what we can do
https://github.com/igorsuhinin/modx-instagram-latest-posts/issues/18#issuecomment-395985319

**Comment by Ilja-developer** [comment]
> > Same issue here.
> > Error log: PHP warning: file_get_contents(https://www.instagram.com/nike/?__a=1): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
> > Any ideas?
> 
> Why it happen
> [#18 (comment)](https://github.com/igorsuhinin/modx-instagram-latest-posts/issues/18#issuecomment-395666015)
> 
> And what we can do
> [#18 (comment)](https://github.com/igorsuhinin/modx-instagram-latest-posts/issues/18#issuecomment-395985319)

Sorry, but I don't understand how I can fix it?

**Comment by Bournwog** [comment]
https://stackoverflow.com/questions/49265339/instagram-a-1-url-not-working-anymore-problems-with-graphql-query-to-get-da
