### ISSUE TITLE
ERROR: The JSON parsing failed

### ISSUE THREAD

**Issue by CeilloNoll** [igorsuhinin/modx-instagram-latest-posts#19]
Thank you for greatest plugin, i was using it in several my projects. But late week i started to get error: The JSON parsing failed.
Can i hope for an update?

**Comment by igorsuhinin** [comment]
Sorry, I don't think I will ever update this code. Currently I do not work with MODX so there is no reason for me to support it anymore :-/ I would be happy if anyone else could take the code and update it.
