### ISSUE TITLE
Ошибка кэша

### ISSUE THREAD

**Issue by kmvit** [igorsuhinin/modx-instagram-latest-posts#8]
Здравствуйте. У меня при вставке сниппета в шаблон выдает такую ошибку /core/cache/includes/elements/modsnippet/22.include.cache.php on line 49. Чистил кэш, не помогает, куда копать? Использую Modx revo 2.6.0

**Comment by igorsuhinin** [comment]
Привет.
Вы используете последнюю версию сниппета 1.5.0?
Ошибка приведена не полностью, должно быть кое-что еще, там как раз подробности, без которых ничего непонятно.

**Comment by kmvit** [comment]
Скачал из репозитория. Версия 1.4.0-pl.

**Comment by igorsuhinin** [comment]
Обновите здесь из кода на github. Я все никак не соберусь сделать обновление для дополнения MODX

**Comment by kmvit** [comment]
Обновил, не помогло

**Comment by igorsuhinin** [comment]
Похоже, у Вас еще устаревшая версия PHP. Посмотрите [сюда](https://github.com/igorsuhinin/modx-instagram-latest-posts/issues/1#issuecomment-291843455)

**Comment by kmvit** [comment]
Спасибо, помогло)
