### ISSUE TITLE
JSON content failed

### ISSUE THREAD

**Issue by zapmedia** [igorsuhinin/modx-instagram-latest-posts#9]
I am using the the snippet as [[!InstagramLatestPosts? &accountName=`nike`]] however I get the following error message "The remote loading of JSON content failed. Please check if your account name is correct."

The MODX error log contains the following: core/cache/includes/elements/modsnippet/30.include.cache.php : 241) PHP warning: file_get_contents(https://www.instagram.com/nike/media/): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

**Comment by zapmedia** [comment]
Now working, I was using version 1.4 from the MODX extras. Updated version not within the extras repository. Thanks

**Comment by igorsuhinin** [comment]
Hi @zapmedia,
Yes, you need to use the updated version which is available here on github.
I haven't updated the MODX extra yet :(
